/***** CREATE DATA_TABLE *****/
CREATE TABLE SUREData(
	SEQNO number NOT NULL,
    INTIME char(14) NOT NULL,
	USERCODE char(30) NOT NULL,
	REQNAME varchar(32) NULL,
	REQPHONE varchar(20) NULL,
	CALLNAME varchar(32) NULL,
	COUNTRY varchar(10) NULL,
	CALLPHONE varchar(20) NOT NULL,
	SUBJECT varchar(120) NULL,
	MSG varchar(4000) NOT NULL,
	REQTIME char(14) NOT NULL,
	SENTTIME char(14) NULL,
	RECVTIME char(14) NULL,
	RESULT char(1) DEFAULT '0' NOT NULL,
	ERRCODE integer NULL,
	KIND char(1) NOT NULL,
	FKCONTENT integer NULL,
	DEPTCODE char(30) NOT NULL,
	BATCHFLAG integer DEFAULT 0 NOT NULL,
	RETRY integer DEFAULT 0 NOT NULL,
	TEMPLATECODE char(14) NULL,
    PRIMARY KEY (SEQNO)
 );


/***** CREATE MMSCONTENTS TABLE *****/
CREATE TABLE MMSContents(
	SeqNo integer NOT NULL,
	FileCnt integer DEFAULT 0 NOT NULL,
	FilePath1 varchar(255) NULL,
	FilePath2 varchar(255) NULL,
	FilePath3 varchar(255) NULL,
    PRIMARY KEY (SEQNO)
);


/***** CREATE LOG TABLE *****/
CREATE TABLE SUREData_Log(
	SEQNO integer NOT NULL,
    INTIME char(14) NOT NULL,
	USERCODE char(30) NOT NULL,
	REQNAME varchar(32) NULL,
	REQPHONE varchar(20) NULL,
	CALLNAME varchar(32) NULL,
	COUNTRY varchar(10) NULL,
	CALLPHONE varchar(20) NOT NULL,
	SUBJECT varchar(120) NULL,
	MSG varchar(4000) NOT NULL,
	REQTIME char(14) NOT NULL,
	SENTTIME char(14) NULL,
	RECVTIME char(14) NULL,
	RESULT char(1) DEFAULT '0' NOT NULL,
	ERRCODE integer NULL,
	KIND char(1) NOT NULL,
	FKCONTENT integer NULL,
	DEPTCODE char(30) NOT NULL,
	BATCHFLAG integer DEFAULT 0 NOT NULL,
	RETRY integer DEFAULT 0 NOT NULL,
	TEMPLATECODE char(14) NULL
 );

 
/***** CREATE INDEX *****/
CREATE INDEX IX_SUREData ON SUREData(RESULT, KIND);


/***** CREATE SEQUENCE *****/
CREATE SEQUENCE SUREData_SEQNO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MMSContents_SEQNO START WITH 1 INCREMENT BY 1;







